### ISSUE TITLE
How to change pdf document

### ISSUE THREAD

**Issue by vinpel** [Yii2Assets/yii2-pdfjs#17]
Hello, 
I'm not very good at Javascript, could you help me to find how to change the document loaded :

1. Open a page with a yii2-pdfjs document who load doc1.pdf
2. Click on a button / link ... 
3. Without relaoding the page, the document is doc2.pdf

Could you help me ?

**Comment by amlopezalonso** [comment]
Hi,
Unfortunately, I'm not into Javascript either. I could help you with PHP instead. Sorry.

**Comment by vinpel** [comment]
This javascript code seem to work :
```javascript
                $('#pdfjs-w0').css('background-color','#404040');
                $('#pdfjs-form-w0').attr('action','/pdfjs?file=%2Fcontroller%2Faction%2F');
                $('#pdfjs-form-w0').submit();
```
